apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-screening
  namespace: resume-screening
spec:
  rules:
    - host: resume-screening.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000
